plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.externalstorage'
version = '0.1.0'

android {
  namespace "expo.modules.externalstorage"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  // JGit needs Java 11+
  compileOptions {
    coreLibraryDesugaringEnabled true
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }
}

dependencies {
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
  implementation 'org.eclipse.jgit:org.eclipse.jgit:6.10.0.202406032230-r'
  implementation "com.squareup.okhttp3:okhttp:4.12.0"
}
